name: Node.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - run: >-
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue"
          "npm run build-storybook --quiet && npx http-server storybook-static --port 6006 --silent"
          "npx wait-on http://127.0.0.1:6006 && npm run test-storybook -- --url=http://127.0.0.1:6006"
      - run: npm run lint
